AWS_ACCESS_KEY_ID: evercam
AWS_SECRET_ACCESS_KEY: evercam
ADMIN_PASSWORD: password1
ADMIN_EMAIL: admin@evercam.io
ADMIN_API_ID: 7168504232c9cbaf57c5f
ADMIN_API_KEY: d46c9f9ca22451c6670f2435c9235cb
SECRET_KEY_BASE: d46c9f9ca22451c6670f2435c9235cb
EVERCAM_DB_NAME: evercam_dev
EVERCAM_DB_USERNAME: evercam
EVERCAM_DB_PASSWORD: evercam
EVERCAM_DB_HOSTNAME: localhost
EVERCAM_DB_PORT: 5432