default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pbrudny
  password: polmuz

development:
  <<: *default
  database: evercam_admin_development

test:
  <<: *default
  database: evercam_admin_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
