default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pbrudny
  password: polmuz

evercam_db_development:
  <<: *default
  database: evercam_dev

development:
  <<: *default
  database: evercam_admin_development

test:
  <<: *default
  database: evercam_admin_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

evercam_db_production:
  <<: *default
  database: <%= ENV['EVERCAM_DB_NAME'] %>
  username: <%= ENV['EVERCAM_DB_USERNAME'] %>
  password: <%= ENV['EVERCAM_DB_PASSWORD'] %>
  host: <%= ENV['EVERCAM_DB_HOSTNAME'] %>
  port: <%= ENV['EVERCAM_DB_PORT'] %>