default: &default
  adapter: postgresql
  encoding: utf8
  schema_search_path: public
  template: template0
  username: pbrudny
  password: polmuz

development:
  <<: *default
  database: evercam_admin_development

test:
  <<: *default
  database: evercam_admin_test

production:
  <<: *default
  database: evercam_admin_production